language: node_js
node_js:
- 6
cache:
  directories:
  - node_modules
script:
- CI=false npm run build
deploy:
  provider: heroku
  app:
    master: block-party-client
    staging: block-party-staging-client
  api_key:
    secure: f95Sq3CLWpbvXjTx8eYWaPVNNF6Q/vdK4iblTEL68qSttXZQxaoddGkTOd7cHRPOgOsFTPaaB1z48hMbNx8MzxyVYZqY3szqpKz49hK2PKsOvTtwljOo9RRzsjSnIo712zzkjXte4rHkgj0zh7V7Wwdbd9gtbilPOsoJ0n+dYuW/cCOm1f009EkW+Rd65LkbCuU2Br6ydsuMuCYbYzXtRrDsRt3y9EuCD92AIotAthcS9cfVo8bvzmZgcEhkeRhpB2qRR67KITN77sm8uEEf4G3DGrnjtQx96KICO3MOc7WRBHhN1EOE128PjjqHb56LfAKz/KpZoVqBP3vrs9W5nHLeest8+Xv/D6Va4Gt5QmP+2UOlZm2tvq58LO3J4IvBGJX3QZOt17lVwnXiwo+W/bSQIJXo5LsVynPZ6OdTaBUwZhcXk6jX40vux8ew3/KVm01Azh8f2W1xQYZWlJZ6DBSD/KUQ4fM8AhVa5NdiJImaWWZdiYuDU2vWpK4DQP81M1lJVT8+8y07y+k2FrLmbtA/QshTfJPR5B6Zlw83CPF6jImoZjsi3T5iZ+2d9y7Ah5HUkimy+zyTM0pxDGE0KcdohoK090lKrj9yIdLkFkEmc/s1r4ZREc2Pt3WOLEVHYSrQfLVBQgBYA6KwdR1uthQlNcBe7Y9YNgufSrh6yRo=
notifications:
  slack:
    secure: LxCTZG9b5hwCeNCWH1nqL6s/0du/5NwRi9as3zPggmst+INq4EcsjvXJR0FP6G7hNL3nVjgpz/gHCRZbWPyleNPAL5QoTQKULM3dNs/2SGZGVAtZQlGMm0TkuM7ITp9PoSNRRd6D4cOSWz9/1N7GKc992k8n8wb9G1ZLhAGu6td1PcU0MzCYLkUs9l7pPAox6mbNizuCkBUpdsH9qT2PSb26x8ezEm7ip8XdRv4HL/xqIKQx09q3xtebO1mVI0MCVMrkpFFYZN50JpqLU4eyX0IkMNTDIhYlDVBYOeOdwaAPWtH9U6So1U1lIm+UjwDEKZhOW6vYQPYLlx2H6hZlZgb1y0OUJJfipBu73XTyfth+05yFH3vJgV2a0SpBwwIZQxbXsMRS9xAnC9zHgw4uFwTQiL2Gtu8IBb2mTdqc1M4gttkEC1w4lBKuMbN/00P+93dDiOf1P4y34maqJunrKQMtLceAcJ3DFzDnVngS+zqHaNWdU3tdpYp8g+gn1CoN3+whuHRSK0ht++ERHf3jZIVlnFkZQ38BAc0AJUm/Z6uu941HAbtpigV69gd52ZrDaXiXlSWNI9DNPi/GGPm4CMA/DE2hahYHvht3yk9YdcXbNrwdrymOX/5GlAKN/XzQ//pttOTiSm/FPtiWUaKTKi4/XfedKmCOoD8gCLsBL/s=
