language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - npm test -- --coverage
  - npm run build
deploy:
  provider: heroku
  app:
    master: block-party-client
    staging: block-party-staging-client
